2025-08-27 12:42:12,608 INFO    MainThread:95037 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-27 12:42:12,608 INFO    MainThread:95037 [wandb_setup.py:_flush():80] Configure stats pid to 95037
2025-08-27 12:42:12,608 INFO    MainThread:95037 [wandb_setup.py:_flush():80] Loading settings from /home/terry/.config/wandb/settings
2025-08-27 12:42:12,608 INFO    MainThread:95037 [wandb_setup.py:_flush():80] Loading settings from /home/terry/gcs-bucket/Distillation/vision/train/wandb/settings
2025-08-27 12:42:12,608 INFO    MainThread:95037 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-27 12:42:12,622 INFO    MainThread:95037 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/terry/gcs-bucket/Distillation/vision/train/wandb/offline-run-20250827_124211-s95f9wum/logs/debug.log
2025-08-27 12:42:12,636 INFO    MainThread:95037 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/terry/gcs-bucket/Distillation/vision/train/wandb/offline-run-20250827_124211-s95f9wum/logs/debug-internal.log
2025-08-27 12:42:12,636 INFO    MainThread:95037 [wandb_init.py:init():830] calling init triggers
2025-08-27 12:42:12,636 INFO    MainThread:95037 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'epochs': 100, 'update_freq': 1, 'model': 'my_vit_b', 'drop_path': 0.1, 'input_size': 224, 'layer_scale_init_value': 1e-06, 'model_ema': True, 'model_ema_decay': 0.9999, 'model_ema_force_cpu': False, 'model_ema_eval': True, 'opt': 'adamw', 'opt_eps': 1e-08, 'opt_betas': None, 'clip_grad': None, 'momentum': 0.9, 'weight_decay': 0.05, 'weight_decay_end': None, 'lr': 0.004, 'layer_decay': 1.0, 'min_lr': 1e-06, 'warmup_epochs': 20, 'warmup_steps': -1, 'color_jitter': 0.4, 'aa': 'rand-m9-mstd0.5-inc1', 'smoothing': 0.1, 'train_interpolation': 'bicubic', 'crop_pct': 0.875, 'reprob': 0.25, 'remode': 'pixel', 'recount': 1, 'resplit': False, 'mixup': 0.8, 'cutmix': 1.0, 'cutmix_minmax': None, 'mixup_prob': 1.0, 'mixup_switch_prob': 0.5, 'mixup_mode': 'batch', 'finetune': '', 'head_init_scale': 1.0, 'model_key': 'model|module', 'model_prefix': '', 'data_path': '/home/terry/gcs-bucket/Distillation/vision/datasets/imagenet-hdf5', 'eval_data_path': None, 'nb_classes': 1000, 'imagenet_default_mean_and_std': True, 'data_set': 'IMNET_HDF5', 'output_dir': '/home/terry/gcs-bucket/Distillation/vision/models/vanilla/b-vanilla', 'log_dir': None, 'device': 'cuda', 'seed': 0, 'resume': '', 'auto_resume': False, 'save_ckpt': True, 'save_ckpt_freq': 1, 'save_ckpt_num': 3, 'start_epoch': 0, 'eval': False, 'dist_eval': True, 'disable_eval': False, 'num_workers': 10, 'pin_mem': True, 'world_size': 1, 'local_rank': -1, 'dist_on_itp': False, 'dist_url': 'env://', 'use_amp': True, 'enable_wandb': True, 'wandb_mode': 'offline', 'wandb_dir': None, 'project': 'ViT-della', 'wandb_ckpt': False, 'experiment': 'b-vanilla', 'kd': False, 'teacher_path': '', 'teacher_arch': '', 'kd_alpha': 0.7, 'kd_temperature': 4.0, 'tpu': True, 'rank': 0, 'gpu': 0, 'dist_backend': 'xla', 'distributed': False, '_wandb': {}}
2025-08-27 12:42:12,636 INFO    MainThread:95037 [wandb_init.py:init():871] starting backend
2025-08-27 12:42:13,076 INFO    MainThread:95037 [wandb_init.py:init():874] sending inform_init request
2025-08-27 12:42:13,390 INFO    MainThread:95037 [wandb_init.py:init():882] backend started and connected
2025-08-27 12:42:13,413 INFO    MainThread:95037 [wandb_init.py:init():953] updated telemetry
2025-08-27 12:42:13,949 INFO    MainThread:95037 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-27 12:42:14,071 INFO    MainThread:95037 [wandb_init.py:init():1029] starting run threads in backend
2025-08-27 12:42:14,401 INFO    MainThread:95037 [wandb_run.py:_console_start():2494] atexit reg
2025-08-27 12:42:14,401 INFO    MainThread:95037 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-27 12:42:14,401 INFO    MainThread:95037 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-27 12:42:14,401 INFO    MainThread:95037 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-27 12:42:14,436 INFO    MainThread:95037 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-27 12:54:53,149 INFO    MsgRouterThr:95037 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
2025-08-27 12:54:53,479 ERROR   MainThread:95037 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 12:54:53,773 ERROR   MainThread:95037 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 12:54:53,773 ERROR   MainThread:95037 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 12:54:53,773 ERROR   MainThread:95037 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 12:54:53,774 ERROR   MainThread:95037 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/terry/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
